In [1]:
import pandas as pd
import numpy as np
import datetime
data = pd.read_csv("with_closed_ations_as________select_app_2020_X5_STORES.CSV")
data

D:\misis\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (6,7) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name,position_name,is_active_action,is_open_action
0,4797513,3847682,-1,7335,2020-03-23 19:57:25.316022+00,Создание кандидата,NaN,NaN,Продавец-кассир,True,False
1,4545953,3714199,-1,24522,2020-01-24 16:57:59.521103+00,Создание кандидата,NaN,NaN,Директор магазина,True,False
2,4600098,3714199,-1,24522,2020-02-05 17:57:55.727051+00,Создание кандидата,NaN,NaN,Директор магазина,True,False
3,4788965,3843286,-1,10613,2020-03-20 16:09:34.454329+00,Создание кандидата,NaN,NaN,Продавец-кассир,True,False
4,4777310,2372866,-1,45445,2020-03-18 13:53:36.124784+00,Создание кандидата,NaN,NaN,Продавец-кассир,True,False
...,...,...,...,...,...,...,...,...,...,...,...
739676,4736341,936507,-1,32061,2020-04-23 16:26:11.80918+00,Не прошел СБ,Вывести из черного списка,NaN,Продавец-кассир,True,True
739677,4734680,2232021,-1,32061,2020-04-23 16:26:11.80918+00,Гайд-интервью,Назначить время для гайд-интервью,NaN,Администратор,True,True
739678,4782853,2753502,-1,32110,2020-04-23 16:26:11.80918+00,Не прошел СБ,Вывести из черного списка,NaN,Продавец-кассир,True,True
739679,4769924,3823657,-1,32110,2020-04-23 16:26:11.80918+00,Не прошел СБ,Вывести из черного списка,NaN,Продавец-кассир,True,True
739680,4683816,862865,-1,32093,2020-04-23 16:26:11.80918+00,Не прошел СБ,Вывести из черного списка,NaN,Продавец-кассир,True,True

In [2]:
le_masque = data['position_name'] == 'Продавец-кассир'
le_masque &= data['is_active_action'] == True
df = data[le_masque]
df

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name,position_name,is_active_action,is_open_action
0,4797513,3847682,-1,7335,2020-03-23 19:57:25.316022+00,Создание кандидата,NaN,NaN,Продавец-кассир,True,False
3,4788965,3843286,-1,10613,2020-03-20 16:09:34.454329+00,Создание кандидата,NaN,NaN,Продавец-кассир,True,False
4,4777310,2372866,-1,45445,2020-03-18 13:53:36.124784+00,Создание кандидата,NaN,NaN,Продавец-кассир,True,False
11,4798971,1253935,-1,9851,2020-03-24 10:39:28.667648+00,Создание кандидата,NaN,NaN,Продавец-кассир,True,False
13,4637426,3352131,-1,7640,2020-02-13 12:44:35.802112+00,Создание кандидата,NaN,NaN,Продавец-кассир,True,False
...,...,...,...,...,...,...,...,...,...,...,...
739675,4825142,2952699,-1,32061,2020-04-23 16:26:11.80918+00,Не прошел СБ,Вывести из черного списка,NaN,Продавец-кассир,True,True
739676,4736341,936507,-1,32061,2020-04-23 16:26:11.80918+00,Не прошел СБ,Вывести из черного списка,NaN,Продавец-кассир,True,True
739678,4782853,2753502,-1,32110,2020-04-23 16:26:11.80918+00,Не прошел СБ,Вывести из черного списка,NaN,Продавец-кассир,True,True
739679,4769924,3823657,-1,32110,2020-04-23 16:26:11.80918+00,Не прошел СБ,Вывести из черного списка,NaN,Продавец-кассир,True,True
739680,4683816,862865,-1,32093,2020-04-23 16:26:11.80918+00,Не прошел СБ,Вывести из черного списка,NaN,Продавец-кассир,True,True

In [3]:
df_new = df.copy()
df_new

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name,position_name,is_active_action,is_open_action
0,4797513,3847682,-1,7335,2020-03-23 19:57:25.316022+00,Создание кандидата,NaN,NaN,Продавец-кассир,True,False
3,4788965,3843286,-1,10613,2020-03-20 16:09:34.454329+00,Создание кандидата,NaN,NaN,Продавец-кассир,True,False
4,4777310,2372866,-1,45445,2020-03-18 13:53:36.124784+00,Создание кандидата,NaN,NaN,Продавец-кассир,True,False
11,4798971,1253935,-1,9851,2020-03-24 10:39:28.667648+00,Создание кандидата,NaN,NaN,Продавец-кассир,True,False
13,4637426,3352131,-1,7640,2020-02-13 12:44:35.802112+00,Создание кандидата,NaN,NaN,Продавец-кассир,True,False
...,...,...,...,...,...,...,...,...,...,...,...
739675,4825142,2952699,-1,32061,2020-04-23 16:26:11.80918+00,Не прошел СБ,Вывести из черного списка,NaN,Продавец-кассир,True,True
739676,4736341,936507,-1,32061,2020-04-23 16:26:11.80918+00,Не прошел СБ,Вывести из черного списка,NaN,Продавец-кассир,True,True
739678,4782853,2753502,-1,32110,2020-04-23 16:26:11.80918+00,Не прошел СБ,Вывести из черного списка,NaN,Продавец-кассир,True,True
739679,4769924,3823657,-1,32110,2020-04-23 16:26:11.80918+00,Не прошел СБ,Вывести из черного списка,NaN,Продавец-кассир,True,True
739680,4683816,862865,-1,32093,2020-04-23 16:26:11.80918+00,Не прошел СБ,Вывести из черного списка,NaN,Продавец-кассир,True,True

In [4]:
def convert(val):
    if val.find(".") == -1:
        if val.find("+") == -1:
            date_time_obj = "Null"
        else:
            val = val[:val.find("+")]
            date_time_obj = datetime.datetime.strptime(val, '%Y-%m-%d %H:%M:%S')
    else:
        val = val[:val.find(".")]
        date_time_obj = datetime.datetime.strptime(val, '%Y-%m-%d %H:%M:%S')
    return date_time_obj

In [5]:
df_new['action_date'] = df_new['action_date'].apply(convert)

In [6]:
df_new = df_new.sort_values(by = ['id_partner', 'action_date'])
df_new

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name,position_name,is_active_action,is_open_action
133855,4492661,530570,-1,48879,2020-01-14 11:49:41,Создание кандидата,NaN,NaN,Продавец-кассир,True,False
67800,4698826,530611,-1,12476,2020-02-27 16:16:21,Создание кандидата,NaN,NaN,Продавец-кассир,True,False
129783,4859533,530654,-1,32944,2020-04-08 09:03:25,Создание кандидата,NaN,NaN,Продавец-кассир,True,False
249942,4859533,530654,26944118,32944,2020-04-08 09:04:16,Обработка,Провести первичную обработку,Подходит,Продавец-кассир,True,False
249941,4859533,530654,26944119,32944,2020-04-08 09:04:17,Обработка,Проверка формы обращения,Не резерв,Продавец-кассир,True,False
...,...,...,...,...,...,...,...,...,...,...,...
662018,4886612,3897226,27106019,32875,2020-04-14 11:09:07,Интервью с руководителем,Узнать результаты интервью с руководителем,Подходит,Продавец-кассир,True,False
662019,4886612,3897226,27106020,32875,2020-04-14 11:09:08,СБ,Подготовить анкету кандидата,Подготовлена,Продавец-кассир,True,False
734844,4886612,3897226,-1,32875,2020-04-23 16:26:11,СБ,Узнать результаты СБ,NaN,Продавец-кассир,True,True
185790,4886610,3897231,-1,30523,2020-04-14 11:08:31,Создание кандидата,NaN,NaN,Продавец-кассир,True,False
473504,4886610,3897231,27106006,30523,2020-04-14 11:08:56,Обработка,Провести первичную обработку,Не подходит,Продавец-кассир,True,False

In [7]:
parthner_array = df_new[df_new['result_name'] == 'Принят']['id_partner'].unique() # время найма по людям
tth=[]
for i in parthner_array:
    parthner = df_new[df_new['id_partner'] == i]
    tth.append(max(parthner['action_date'])-min(parthner['action_date']))
tth

[Timedelta('10 days 23:00:15'),
 Timedelta('85 days 01:03:53'),
 Timedelta('10 days 02:15:04'),
 Timedelta('6 days 03:41:56'),
 Timedelta('54 days 04:59:23'),
 Timedelta('13 days 23:32:28'),
 Timedelta('51 days 21:03:29'),
 Timedelta('6 days 03:56:40'),
 Timedelta('3 days 19:52:13'),
 Timedelta('7 days 05:22:12'),
 Timedelta('2 days 02:05:26'),
 Timedelta('13 days 01:55:49'),
 Timedelta('78 days 05:14:27'),
 Timedelta('12 days 01:06:29'),
 Timedelta('5 days 23:44:06'),
 Timedelta('7 days 06:26:02'),
 Timedelta('0 days 00:00:30'),
 Timedelta('9 days 02:39:23'),
 Timedelta('8 days 22:38:24'),
 Timedelta('15 days 03:30:35'),
 Timedelta('19 days 23:41:59'),
 Timedelta('1 days 23:58:55'),
 Timedelta('4 days 08:30:52'),
 Timedelta('7 days 06:25:02'),
 Timedelta('7 days 18:59:44'),
 Timedelta('5 days 01:15:09'),
 Timedelta('10 days 04:10:39'),
 Timedelta('13 days 03:08:24'),
 Timedelta('21 days 04:20:39'),
 Timedelta('4 days 20:19:11'),
 Timedelta('21 days 22:10:22'),
 Timedelta('5 days 00:15:20'),
 Timedelta('10 days 20:05:59'),
 Timedelta('95 days 04:12:00'),
 Timedelta('14 days 02:11:02'),
 Timedelta('17 days 22:40:30'),
 Timedelta('7 days 03:02:38'),
 Timedelta('0 days 00:00:54'),
 Timedelta('10 days 21:52:43'),
 Timedelta('14 days 01:26:42'),
 Timedelta('9 days 18:49:22'),
 Timedelta('6 days 02:28:33'),
 Timedelta('11 days 00:14:04'),
 Timedelta('21 days 22:09:03'),
 Timedelta('17 days 02:23:46'),
 Timedelta('23 days 03:38:51'),
 Timedelta('7 days 01:30:30'),
 Timedelta('13 days 05:55:13'),
 Timedelta('2 days 01:59:08'),
 Timedelta('17 days 03:50:47'),
 Timedelta('14 days 18:54:59'),
 Timedelta('26 days 17:29:13'),
 Timedelta('8 days 02:49:13'),
 Timedelta('53 days 18:51:34'),
 Timedelta('0 days 00:00:27'),
 Timedelta('73 days 06:45:10'),
 Timedelta('0 days 00:00:54'),
 Timedelta('8 days 04:02:27'),
 Timedelta('13 days 07:26:36'),
 Timedelta('4 days 22:44:39'),
 Timedelta('5 days 20:55:07'),
 Timedelta('9 days 00:46:23'),
 Timedelta('75 days 20:25:33'),
 Timedelta('8 days 01:22:09'),
 Timedelta('11 days 02:32:16'),
 Timedelta('49 days 04:30:09'),
 Timedelta('11 days 23:55:01'),
 Timedelta('6 days 18:49:53'),
 Timedelta('31 days 03:38:33'),
 Timedelta('16 days 05:50:51'),
 Timedelta('5 days 21:10:34'),
 Timedelta('26 days 04:25:25'),
 Timedelta('19 days 16:49:26'),
 Timedelta('8 days 05:55:14'),
 Timedelta('12 days 01:26:50'),
 Timedelta('34 days 05:18:21'),
 Timedelta('6 days 19:10:29'),
 Timedelta('26 days 23:12:56'),
 Timedelta('9 days 19:41:01'),
 Timedelta('8 days 11:56:50'),
 Timedelta('4 days 19:42:11'),
 Timedelta('16 days 01:30:31'),
 Timedelta('22 days 00:01:02'),
 Timedelta('31 days 22:42:42'),
 Timedelta('12 days 00:01:32'),
 Timedelta('4 days 04:05:17'),
 Timedelta('16 days 19:31:36'),
 Timedelta('21 days 04:25:34'),
 Timedelta('0 days 00:00:32'),
 Timedelta('5 days 05:50:14'),
 Timedelta('8 days 01:47:01'),
 Timedelta('18 days 02:06:36'),
 Timedelta('6 days 21:54:02'),
 Timedelta('0 days 00:00:35'),
 Timedelta('21 days 08:01:59'),
 Timedelta('0 days 00:00:23'),
 Timedelta('12 days 05:52:16'),
 Timedelta('7 days 20:15:01'),
 Timedelta('5 days 04:31:49'),
 Timedelta('0 days 00:00:29'),
 Timedelta('0 days 00:00:34'),
 Timedelta('0 days 00:00:38'),
 Timedelta('0 days 00:00:26'),
 Timedelta('43 days 02:56:03'),
 Timedelta('21 days 07:50:17'),
 Timedelta('7 days 06:21:39'),
 Timedelta('14 days 00:05:11'),
 Timedelta('0 days 00:00:25'),
 Timedelta('27 days 18:53:14'),
 Timedelta('12 days 18:44:44'),
 Timedelta('0 days 00:00:28'),
 Timedelta('16 days 01:09:09'),
 Timedelta('57 days 00:05:09'),
 Timedelta('2 days 07:41:05'),
 Timedelta('21 days 04:37:40'),
 Timedelta('0 days 00:00:22'),
 Timedelta('0 days 00:00:52'),
 Timedelta('26 days 04:46:48'),
 Timedelta('8 days 01:10:24'),
 Timedelta('6 days 01:31:59'),
 Timedelta('19 days 23:41:08'),
 Timedelta('0 days 00:00:23'),
 Timedelta('20 days 04:16:01'),
 Timedelta('0 days 00:19:13'),
 Timedelta('0 days 00:00:28'),
 Timedelta('6 days 06:54:57'),
 Timedelta('12 days 04:09:08'),
 Timedelta('6 days 23:15:30'),
 Timedelta('12 days 03:43:42'),
 Timedelta('5 days 03:42:00'),
 Timedelta('26 days 03:33:11'),
 Timedelta('0 days 00:00:32'),
 Timedelta('16 days 00:02:35'),
 Timedelta('10 days 06:36:56'),
 Timedelta('4 days 03:01:55'),
 Timedelta('25 days 01:50:50'),
 Timedelta('16 days 23:36:20'),
 Timedelta('4 days 05:20:53'),
 Timedelta('84 days 21:40:51'),
 Timedelta('13 days 14:33:21'),
 Timedelta('7 days 04:43:41'),
 Timedelta('10 days 02:23:42'),
 Timedelta('8 days 21:19:36'),
 Timedelta('5 days 22:04:19'),
 Timedelta('21 days 04:49:58'),
 Timedelta('2 days 19:02:24'),
 Timedelta('15 days 20:31:03'),
 Timedelta('24 days 17:34:30'),
 Timedelta('11 days 17:35:08'),
 Timedelta('5 days 02:24:07'),
 Timedelta('6 days 00:39:05'),
 Timedelta('8 days 03:55:53'),
 Timedelta('9 days 23:45:41'),
 Timedelta('15 days 18:51:29'),
 Timedelta('5 days 22:02:04'),
 Timedelta('28 days 07:21:31'),
 Timedelta('20 days 23:25:14'),
 Timedelta('12 days 07:53:17'),
 Timedelta('8 days 05:56:28'),
 Timedelta('4 days 03:51:03'),
 Timedelta('2 days 07:46:38'),
 Timedelta('7 days 23:55:28'),
 Timedelta('0 days 00:01:00'),
 Timedelta('0 days 00:00:37'),
 Timedelta('4 days 00:02:13'),
 Timedelta('46 days 02:55:05'),
 Timedelta('5 days 08:05:04'),
 Timedelta('7 days 00:03:08'),
 Timedelta('10 days 02:11:02'),
 Timedelta('16 days 04:52:18'),
 Timedelta('12 days 06:02:16'),
 Timedelta('0 days 00:01:00'),
 Timedelta('7 days 23:18:38'),
 Timedelta('12 days 18:59:02'),
 Timedelta('10 days 04:35:29'),
 Timedelta('0 days 00:00:27'),
 Timedelta('5 days 06:48:59'),
 Timedelta('10 days 21:03:38'),
 Timedelta('7 days 21:24:36'),
 Timedelta('7 days 23:01:54'),
 Timedelta('16 days 01:26:48'),
 Timedelta('15 days 04:41:43'),
 Timedelta('11 days 02:33:47'),
 Timedelta('3 days 01:12:12'),
 Timedelta('6 days 04:05:00'),
 Timedelta('7 days 17:20:10'),
 Timedelta('33 days 22:45:38'),
 Timedelta('10 days 22:17:11'),
 Timedelta('4 days 08:44:00'),
 Timedelta('9 days 11:38:25'),
 Timedelta('5 days 19:36:15'),
 Timedelta('12 days 19:44:32'),
 Timedelta('9 days 06:48:07'),
 Timedelta('41 days 04:44:18'),
 Timedelta('6 days 23:17:00'),
 Timedelta('6 days 02:24:54'),
 Timedelta('63 days 06:32:37'),
 Timedelta('30 days 05:22:36'),
 Timedelta('1 days 19:56:24'),
 Timedelta('7 days 00:41:56'),
 Timedelta('5 days 06:07:55'),
 Timedelta('12 days 01:08:13'),
 Timedelta('0 days 00:00:25'),
 Timedelta('6 days 19:06:34'),
 Timedelta('10 days 01:25:32'),
 Timedelta('12 days 02:14:58'),
 Timedelta('14 days 12:37:34'),
 Timedelta('0 days 00:00:19'),
 Timedelta('4 days 03:08:17'),
 Timedelta('14 days 06:26:52'),
 Timedelta('3 days 02:49:27'),
 Timedelta('7 days 07:22:20'),
 Timedelta('5 days 20:20:14'),
 Timedelta('13 days 17:56:28'),
 Timedelta('4 days 02:39:37'),
 Timedelta('21 days 01:39:24'),
 Timedelta('2 days 00:48:55'),
 Timedelta('8 days 02:06:41'),
 Timedelta('3 days 00:09:14'),
 Timedelta('12 days 21:59:35'),
 Timedelta('19 days 22:53:04'),
 Timedelta('13 days 04:04:05'),
 Timedelta('46 days 23:02:08'),
 Timedelta('46 days 03:13:54'),
 Timedelta('42 days 03:36:12'),
 Timedelta('42 days 06:00:31'),
 Timedelta('23 days 23:15:42'),
 Timedelta('0 days 00:00:33'),
 Timedelta('13 days 02:06:37'),
 Timedelta('0 days 00:00:30'),
 Timedelta('0 days 00:00:49'),
 Timedelta('16 days 21:38:12'),
 Timedelta('0 days 00:00:37'),
 Timedelta('4 days 04:01:07'),
 Timedelta('14 days 00:24:34'),
 Timedelta('7 days 23:44:52'),
 Timedelta('9 days 06:34:13'),
 Timedelta('5 days 21:39:06'),
 Timedelta('4 days 03:43:48'),
 Timedelta('12 days 05:06:28'),
 Timedelta('8 days 00:04:48'),
 Timedelta('2 days 00:44:01'),
 Timedelta('14 days 20:23:47'),
 Timedelta('19 days 18:36:49'),
 Timedelta('13 days 20:18:38'),
 Timedelta('6 days 22:49:41'),
 Timedelta('0 days 00:00:38'),
 Timedelta('14 days 02:52:27'),
 Timedelta('12 days 19:12:38'),
 Timedelta('15 days 00:12:22'),
 Timedelta('7 days 06:50:03'),
 Timedelta('6 days 00:33:14'),
 Timedelta('14 days 21:56:56'),
 Timedelta('8 days 03:07:49'),
 Timedelta('55 days 03:09:28'),
 Timedelta('8 days 12:02:09'),
 Timedelta('7 days 04:18:50'),
 Timedelta('5 days 17:38:51'),
 Timedelta('5 days 05:35:12'),
 Timedelta('11 days 22:05:03'),
 Timedelta('10 days 23:28:24'),
 Timedelta('0 days 00:00:26'),
 Timedelta('49 days 01:23:06'),
 Timedelta('24 days 03:27:47'),
 Timedelta('0 days 00:00:58'),
 Timedelta('0 days 00:00:39'),
 Timedelta('63 days 07:02:33'),
 Timedelta('5 days 23:54:54'),
 Timedelta('19 days 23:06:59'),
 Timedelta('41 days 05:34:02'),
 Timedelta('12 days 02:02:51'),
 Timedelta('10 days 23:57:14'),
 Timedelta('0 days 00:00:29'),
 Timedelta('22 days 01:16:01'),
 Timedelta('11 days 22:00:47'),
 Timedelta('17 days 00:45:00'),
 Timedelta('19 days 04:22:20'),
 Timedelta('6 days 03:33:11'),
 Timedelta('8 days 21:51:25'),
 Timedelta('15 days 04:44:06'),
 Timedelta('11 days 01:00:58'),
 Timedelta('21 days 01:39:22'),
 Timedelta('21 days 05:30:11'),
 Timedelta('0 days 00:00:28'),
 Timedelta('6 days 01:40:26'),
 Timedelta('0 days 00:01:00'),
 Timedelta('7 days 02:14:30'),
 Timedelta('16 days 01:36:03'),
 Timedelta('14 days 04:53:37'),
 Timedelta('9 days 03:01:50'),
 Timedelta('13 days 06:05:32'),
 Timedelta('49 days 21:32:13'),
 Timedelta('0 days 00:00:45'),
 Timedelta('57 days 01:50:16'),
 Timedelta('15 days 01:54:46'),
 Timedelta('0 days 00:01:03'),
 Timedelta('5 days 21:39:53'),
 Timedelta('0 days 00:00:43'),
 Timedelta('6 days 23:31:09'),
 Timedelta('0 days 00:00:37'),
 Timedelta('55 days 22:55:16'),
 Timedelta('10 days 05:20:28'),
 Timedelta('7 days 04:14:53'),
 Timedelta('11 days 03:36:42'),
 Timedelta('0 days 00:01:09'),
 Timedelta('5 days 00:48:35'),
 Timedelta('24 days 01:06:15'),
 Timedelta('74 days 02:33:49'),
 Timedelta('2 days 22:08:05'),
 Timedelta('0 days 00:00:37'),
 Timedelta('69 days 01:20:45'),
 Timedelta('15 days 20:38:29'),
 Timedelta('9 days 01:43:56'),
 Timedelta('10 days 07:55:01'),
 Timedelta('14 days 23:56:14'),
 Timedelta('9 days 20:46:55'),
 Timedelta('10 days 20:15:35'),
 Timedelta('6 days 08:32:01'),
 Timedelta('13 days 20:57:25'),
 Timedelta('24 days 02:01:57'),
 Timedelta('7 days 19:23:43'),
 Timedelta('7 days 03:32:28'),
 Timedelta('4 days 05:52:20'),
 Timedelta('9 days 22:08:37'),
 Timedelta('53 days 07:21:50'),
 Timedelta('23 days 03:29:05'),
 Timedelta('8 days 22:48:35'),
 Timedelta('22 days 03:12:56'),
 Timedelta('3 days 00:08:53'),
 Timedelta('13 days 00:58:55'),
 Timedelta('19 days 21:43:30'),
 Timedelta('13 days 22:05:11'),
 Timedelta('13 days 02:35:36'),
 Timedelta('0 days 00:00:28'),
 Timedelta('8 days 02:23:45'),
 Timedelta('40 days 03:26:21'),
 Timedelta('14 days 05:18:13'),
 Timedelta('9 days 00:19:25'),
 Timedelta('10 days 06:15:52'),
 Timedelta('17 days 05:52:13'),
 Timedelta('7 days 07:26:33'),
 Timedelta('16 days 07:14:18'),
 Timedelta('22 days 02:57:36'),
 Timedelta('9 days 01:51:04'),
 Timedelta('11 days 04:00:41'),
 Timedelta('5 days 00:49:18'),
 Timedelta('0 days 00:00:26'),
 Timedelta('5 days 21:37:40'),
 Timedelta('3 days 22:24:23'),
 Timedelta('0 days 00:00:54'),
 Timedelta('20 days 23:45:19'),
 Timedelta('16 days 23:19:40'),
 Timedelta('29 days 21:06:30'),
 Timedelta('10 days 01:39:34'),
 Timedelta('11 days 05:06:31'),
 Timedelta('11 days 03:54:30'),
 Timedelta('21 days 00:42:46'),
 Timedelta('5 days 22:26:46'),
 Timedelta('15 days 03:14:40'),
 Timedelta('0 days 00:00:30'),
 Timedelta('14 days 03:16:49'),
 Timedelta('12 days 18:42:39'),
 Timedelta('7 days 18:51:39'),
 Timedelta('7 days 00:22:30'),
 Timedelta('18 days 01:30:02'),
 Timedelta('6 days 05:39:52'),
 Timedelta('15 days 00:40:40'),
 Timedelta('10 days 00:30:07'),
 Timedelta('16 days 01:44:39'),
 Timedelta('13 days 18:25:41'),
 Timedelta('3 days 03:21:30'),
 Timedelta('8 days 04:14:41'),
 Timedelta('54 days 07:06:04'),
 Timedelta('6 days 06:22:39'),
 Timedelta('23 days 19:54:07'),
 Timedelta('16 days 00:14:06'),
 Timedelta('4 days 03:35:48'),
 Timedelta('4 days 22:55:21'),
 Timedelta('0 days 00:00:35'),
 Timedelta('14 days 00:07:33'),
 Timedelta('3 days 07:28:27'),
 Timedelta('11 days 00:15:20'),
 Timedelta('0 days 00:00:37'),
 Timedelta('5 days 00:24:46'),
 Timedelta('7 days 03:05:13'),
 Timedelta('0 days 00:00:32'),
 Timedelta('24 days 07:11:43'),
 Timedelta('35 days 01:03:57'),
 Timedelta('13 days 21:48:28'),
 Timedelta('0 days 00:00:31'),
 Timedelta('6 days 16:34:12'),
 Timedelta('30 days 04:47:21'),
 Timedelta('5 days 03:13:04'),
 Timedelta('7 days 06:43:52'),
 Timedelta('10 days 03:10:07'),
 Timedelta('3 days 03:34:32'),
 Timedelta('2 days 02:10:20'),
 Timedelta('25 days 02:07:44'),
 Timedelta('22 days 22:38:16'),
 Timedelta('10 days 04:20:29'),
 Timedelta('17 days 22:29:33'),
 Timedelta('10 days 00:23:57'),
 Timedelta('10 days 22:53:46'),
 Timedelta('6 days 18:00:53'),
 Timedelta('18 days 01:19:24'),
 Timedelta('42 days 23:45:07'),
 Timedelta('3 days 06:07:35'),
 Timedelta('8 days 06:48:10'),
 Timedelta('18 days 02:03:47'),
 Timedelta('3 days 22:05:25'),
 Timedelta('8 days 20:15:32'),
 Timedelta('8 days 01:31:03'),
 Timedelta('4 days 23:50:34'),
 Timedelta('0 days 00:00:34'),
 Timedelta('17 days 02:44:00'),
 Timedelta('8 days 21:03:23'),
 Timedelta('6 days 22:30:44'),
 Timedelta('76 days 01:04:04'),
 Timedelta('46 days 19:15:28'),
 Timedelta('36 days 06:41:03'),
 Timedelta('4 days 00:00:19'),
 Timedelta('10 days 07:35:40'),
 Timedelta('4 days 12:12:43'),
 Timedelta('0 days 00:00:47'),
 Timedelta('6 days 21:37:30'),
 Timedelta('28 days 10:12:28'),
 Timedelta('20 days 02:20:15'),
 Timedelta('0 days 00:00:25'),
 Timedelta('12 days 04:14:17'),
 Timedelta('7 days 10:30:28'),
 Timedelta('3 days 22:55:24'),
 Timedelta('7 days 07:13:28'),
 Timedelta('14 days 18:25:56'),
 Timedelta('16 days 00:20:55'),
 Timedelta('1 days 05:45:09'),
 Timedelta('6 days 01:38:17'),
 Timedelta('9 days 22:30:10'),
 Timedelta('7 days 04:00:58'),
 Timedelta('4 days 15:49:16'),
 Timedelta('5 days 05:45:22'),
 Timedelta('6 days 00:27:16'),
 Timedelta('4 days 01:10:23'),
 Timedelta('7 days 06:32:20'),
 Timedelta('35 days 07:11:06'),
 Timedelta('10 days 23:29:28'),
 Timedelta('47 days 05:06:24'),
 Timedelta('18 days 05:18:11'),
 Timedelta('20 days 02:00:23'),
 Timedelta('12 days 21:41:47'),
 Timedelta('9 days 00:33:10'),
 Timedelta('0 days 00:00:48'),
 Timedelta('11 days 06:20:44'),
 Timedelta('4 days 00:31:29'),
 Timedelta('0 days 00:00:33'),
 Timedelta('14 days 16:30:31'),
 Timedelta('26 days 03:16:14'),
 Timedelta('6 days 22:47:38'),
 Timedelta('19 days 21:45:25'),
 Timedelta('34 days 02:51:14'),
 Timedelta('17 days 06:34:46'),
 Timedelta('11 days 23:58:56'),
 Timedelta('28 days 23:27:39'),
 Timedelta('6 days 06:00:41'),
 Timedelta('7 days 00:27:04'),
 Timedelta('23 days 18:45:40'),
 Timedelta('19 days 04:53:05'),
 Timedelta('4 days 09:25:28'),
 Timedelta('0 days 21:10:40'),
 Timedelta('8 days 22:05:34'),
 Timedelta('6 days 23:20:06'),
 Timedelta('5 days 13:16:12'),
 Timedelta('11 days 05:00:22'),
 Timedelta('7 days 02:43:02'),
 Timedelta('12 days 00:11:50'),
 Timedelta('9 days 02:02:09'),
 Timedelta('15 days 17:48:54'),
 Timedelta('4 days 00:09:24'),
 Timedelta('3 days 02:16:50'),
 Timedelta('19 days 06:22:51'),
 Timedelta('14 days 00:55:27'),
 Timedelta('11 days 00:12:53'),
 Timedelta('11 days 22:03:38'),
 Timedelta('20 days 02:09:29'),
 Timedelta('6 days 02:08:34'),
 Timedelta('13 days 06:35:04'),
 Timedelta('75 days 03:52:49'),
 Timedelta('18 days 01:12:57'),
 Timedelta('16 days 00:09:04'),
 Timedelta('6 days 00:21:12'),
 Timedelta('26 days 00:18:26'),
 Timedelta('0 days 00:01:09'),
 Timedelta('57 days 23:11:59'),
 Timedelta('4 days 23:03:59'),
 Timedelta('14 days 02:55:38'),
 Timedelta('22 days 07:12:31'),
 Timedelta('8 days 22:37:01'),
 Timedelta('9 days 07:09:47'),
 Timedelta('12 days 03:13:08'),
 Timedelta('3 days 00:01:20'),
 Timedelta('7 days 03:39:01'),
 Timedelta('46 days 17:44:46'),
 Timedelta('3 days 07:10:58'),
 Timedelta('3 days 21:48:01'),
 Timedelta('2 days 21:41:54'),
 Timedelta('17 days 02:13:49'),
 Timedelta('12 days 01:46:41'),
 Timedelta('34 days 05:35:07'),
 Timedelta('19 days 11:00:21'),
 Timedelta('6 days 01:59:32'),
 Timedelta('24 days 04:08:44'),
 Timedelta('4 days 23:27:52'),
 Timedelta('0 days 00:00:41'),
 Timedelta('34 days 20:01:01'),
 Timedelta('4 days 21:31:03'),
 Timedelta('2 days 03:37:55'),
 Timedelta('8 days 03:17:03'),
 Timedelta('21 days 20:34:31'),
 Timedelta('0 days 00:00:32'),
 Timedelta('4 days 21:48:02'),
 Timedelta('10 days 22:50:53'),
 Timedelta('11 days 10:22:33'),
 Timedelta('6 days 19:03:18'),
 Timedelta('25 days 03:49:52'),
 Timedelta('7 days 19:32:22'),
 Timedelta('14 days 09:03:04'),
 Timedelta('12 days 02:49:08'),
 Timedelta('4 days 00:14:53'),
 Timedelta('11 days 01:29:58'),
 Timedelta('9 days 05:34:14'),
 Timedelta('5 days 08:40:55'),
 Timedelta('10 days 06:27:58'),
 Timedelta('6 days 17:13:17'),
 Timedelta('21 days 18:16:51'),
 Timedelta('4 days 12:14:07'),
 Timedelta('10 days 06:17:01'),
 Timedelta('3 days 03:42:39'),
 Timedelta('6 days 23:01:13'),
 Timedelta('24 days 08:51:32'),
 Timedelta('10 days 22:38:14'),
 Timedelta('0 days 00:00:30'),
 Timedelta('13 days 06:52:45'),
 Timedelta('4 days 01:09:40'),
 Timedelta('3 days 04:20:00'),
 Timedelta('25 days 03:58:14'),
 Timedelta('0 days 00:00:35'),
 Timedelta('71 days 05:41:17'),
 Timedelta('12 days 06:32:10'),
 Timedelta('5 days 11:48:00'),
 Timedelta('28 days 02:09:34'),
 Timedelta('6 days 00:56:55'),
 Timedelta('8 days 05:10:51'),
 Timedelta('5 days 07:01:49'),
 Timedelta('84 days 23:05:02'),
 Timedelta('10 days 02:43:03'),
 Timedelta('12 days 01:53:21'),
 Timedelta('13 days 07:41:43'),
 Timedelta('9 days 02:39:26'),
 Timedelta('7 days 02:22:58'),
 Timedelta('4 days 01:41:23'),
 Timedelta('3 days 03:29:04'),
 Timedelta('7 days 23:07:20'),
 Timedelta('7 days 23:12:43'),
 Timedelta('7 days 19:50:02'),
 Timedelta('13 days 02:22:22'),
 Timedelta('12 days 03:59:51'),
 Timedelta('35 days 21:48:45'),
 Timedelta('37 days 04:43:25'),
 Timedelta('2 days 03:08:21'),
 Timedelta('42 days 11:59:10'),
 Timedelta('0 days 00:00:37'),
 Timedelta('6 days 23:49:38'),
 Timedelta('6 days 22:09:39'),
 Timedelta('0 days 00:03:17'),
 Timedelta('21 days 02:44:29'),
 Timedelta('0 days 00:00:37'),
 Timedelta('0 days 00:00:24'),
 Timedelta('0 days 00:00:25'),
 Timedelta('4 days 06:00:51'),
 Timedelta('9 days 00:11:51'),
 Timedelta('6 days 02:42:12'),
 Timedelta('8 days 00:39:05'),
 Timedelta('19 days 01:16:40'),
 Timedelta('31 days 07:44:26'),
 Timedelta('20 days 22:39:11'),
 Timedelta('6 days 02:27:08'),
 Timedelta('10 days 04:02:33'),
 Timedelta('6 days 21:09:13'),
 Timedelta('9 days 20:42:59'),
 Timedelta('19 days 03:54:56'),
 Timedelta('17 days 06:03:28'),
 Timedelta('3 days 02:31:02'),
 Timedelta('8 days 04:15:18'),
 Timedelta('15 days 03:06:20'),
 Timedelta('0 days 00:00:59'),
 Timedelta('20 days 05:41:34'),
 Timedelta('18 days 23:47:48'),
 Timedelta('0 days 00:03:27'),
 Timedelta('5 days 05:21:00'),
 Timedelta('6 days 03:13:08'),
 Timedelta('20 days 00:48:54'),
 Timedelta('27 days 23:27:54'),
 Timedelta('7 days 00:11:27'),
 Timedelta('13 days 00:16:01'),
 Timedelta('7 days 04:13:31'),
 Timedelta('20 days 10:02:12'),
 Timedelta('0 days 00:00:32'),
 Timedelta('14 days 04:00:42'),
 Timedelta('58 days 05:15:52'),
 Timedelta('9 days 00:35:28'),
 Timedelta('35 days 02:09:55'),
 Timedelta('11 days 23:47:58'),
 Timedelta('10 days 02:49:16'),
 Timedelta('3 days 21:20:37'),
 Timedelta('7 days 03:27:01'),
 Timedelta('30 days 06:07:20'),
 Timedelta('2 days 20:44:05'),
 Timedelta('10 days 02:51:41'),
 Timedelta('0 days 00:00:48'),
 Timedelta('8 days 05:03:25'),
 Timedelta('7 days 22:52:01'),
 Timedelta('7 days 08:46:43'),
 Timedelta('9 days 23:15:04'),
 Timedelta('19 days 04:00:25'),
 Timedelta('67 days 05:15:33'),
 Timedelta('14 days 04:11:56'),
 Timedelta('24 days 21:03:06'),
 Timedelta('13 days 04:39:21'),
 Timedelta('26 days 14:33:59'),
 Timedelta('7 days 03:34:36'),
 Timedelta('0 days 00:01:09'),
 Timedelta('12 days 10:05:20'),
 Timedelta('2 days 08:20:43'),
 Timedelta('58 days 19:23:30'),
 Timedelta('6 days 17:35:01'),
 Timedelta('0 days 00:00:25'),

In [8]:
parthner_array = df_new[df_new['result_name'] == 'Принят']['id_applicant'].unique() # время найма по заявкам
tth=[]
for i in parthner_array:
    parthner = df_new[df_new['id_applicant'] == i]
    tth.append(max(parthner['action_date'])-min(parthner['action_date']))
tth

[Timedelta('9 days 00:12:24'),
 Timedelta('0 days 00:00:53'),
 Timedelta('10 days 02:15:04'),
 Timedelta('6 days 03:41:56'),
 Timedelta('0 days 00:04:21'),
 Timedelta('13 days 23:32:28'),
 Timedelta('0 days 00:01:43'),
 Timedelta('6 days 03:56:40'),
 Timedelta('3 days 19:52:13'),
 Timedelta('7 days 05:22:12'),
 Timedelta('2 days 02:05:26'),
 Timedelta('13 days 01:55:49'),
 Timedelta('0 days 00:00:38'),
 Timedelta('12 days 01:06:29'),
 Timedelta('0 days 00:00:35'),
 Timedelta('0 days 00:00:36'),
 Timedelta('0 days 00:00:30'),
 Timedelta('9 days 02:39:23'),
 Timedelta('8 days 22:38:24'),
 Timedelta('0 days 00:00:23'),
 Timedelta('7 days 20:44:14'),
 Timedelta('1 days 23:58:55'),
 Timedelta('4 days 08:30:52'),
 Timedelta('7 days 06:25:02'),
 Timedelta('0 days 00:00:36'),
 Timedelta('5 days 01:15:09'),
 Timedelta('0 days 00:04:25'),
 Timedelta('13 days 03:08:24'),
 Timedelta('21 days 04:20:39'),
 Timedelta('0 days 00:00:56'),
 Timedelta('0 days 00:00:37'),
 Timedelta('0 days 00:01:29'),
 Timedelta('10 days 20:05:59'),
 Timedelta('5 days 00:44:21'),
 Timedelta('14 days 02:11:02'),
 Timedelta('9 days 22:36:17'),
 Timedelta('0 days 00:00:48'),
 Timedelta('0 days 00:00:54'),
 Timedelta('10 days 21:52:43'),
 Timedelta('14 days 01:26:42'),
 Timedelta('9 days 18:49:22'),
 Timedelta('6 days 02:28:33'),
 Timedelta('0 days 00:01:00'),
 Timedelta('0 days 00:00:36'),
 Timedelta('17 days 02:23:46'),
 Timedelta('23 days 03:38:51'),
 Timedelta('2 days 01:19:01'),
 Timedelta('13 days 05:55:13'),
 Timedelta('2 days 01:59:08'),
 Timedelta('17 days 03:50:47'),
 Timedelta('14 days 18:54:59'),
 Timedelta('0 days 00:00:31'),
 Timedelta('0 days 00:01:11'),
 Timedelta('10 days 22:35:34'),
 Timedelta('0 days 00:00:27'),
 Timedelta('0 days 00:00:33'),
 Timedelta('0 days 00:00:54'),
 Timedelta('8 days 04:02:27'),
 Timedelta('10 days 02:45:44'),
 Timedelta('4 days 22:44:39'),
 Timedelta('5 days 20:55:07'),
 Timedelta('0 days 00:00:58'),
 Timedelta('4 days 21:07:14'),
 Timedelta('0 days 00:00:28'),
 Timedelta('11 days 02:32:16'),
 Timedelta('49 days 04:30:09'),
 Timedelta('0 days 00:00:59'),
 Timedelta('6 days 18:49:53'),
 Timedelta('0 days 00:00:41'),
 Timedelta('16 days 05:50:51'),
 Timedelta('5 days 21:10:34'),
 Timedelta('0 days 00:00:39'),
 Timedelta('19 days 16:49:26'),
 Timedelta('8 days 01:13:20'),
 Timedelta('12 days 01:26:50'),
 Timedelta('0 days 00:00:43'),
 Timedelta('6 days 19:10:29'),
 Timedelta('26 days 23:12:56'),
 Timedelta('9 days 19:41:01'),
 Timedelta('5 days 05:20:37'),
 Timedelta('4 days 19:42:11'),
 Timedelta('16 days 01:30:31'),
 Timedelta('0 days 00:00:37'),
 Timedelta('0 days 00:00:36'),
 Timedelta('2 days 02:01:02'),
 Timedelta('4 days 04:05:17'),
 Timedelta('0 days 00:00:27'),
 Timedelta('21 days 04:25:34'),
 Timedelta('0 days 00:00:32'),
 Timedelta('0 days 00:00:30'),
 Timedelta('0 days 00:00:26'),
 Timedelta('18 days 02:06:36'),
 Timedelta('6 days 21:54:02'),
 Timedelta('0 days 00:00:35'),
 Timedelta('21 days 08:01:59'),
 Timedelta('0 days 00:00:23'),
 Timedelta('12 days 05:52:16'),
 Timedelta('7 days 20:15:01'),
 Timedelta('5 days 04:31:49'),
 Timedelta('0 days 00:00:29'),
 Timedelta('0 days 00:00:34'),
 Timedelta('0 days 00:00:38'),
 Timedelta('0 days 00:00:26'),
 Timedelta('4 days 20:04:00'),
 Timedelta('0 days 00:11:55'),
 Timedelta('7 days 06:21:39'),
 Timedelta('14 days 00:05:11'),
 Timedelta('0 days 00:00:25'),
 Timedelta('0 days 00:00:28'),
 Timedelta('0 days 00:00:42'),
 Timedelta('0 days 00:00:28'),
 Timedelta('0 days 00:00:25'),
 Timedelta('14 days 00:03:38'),
 Timedelta('2 days 07:41:05'),
 Timedelta('8 days 00:00:33'),
 Timedelta('0 days 00:00:22'),
 Timedelta('0 days 00:00:52'),
 Timedelta('14 days 03:16:09'),
 Timedelta('8 days 01:10:24'),
 Timedelta('6 days 01:31:59'),
 Timedelta('0 days 00:00:48'),
 Timedelta('0 days 00:00:23'),
 Timedelta('0 days 00:00:31'),
 Timedelta('0 days 00:19:13'),
 Timedelta('0 days 00:00:28'),
 Timedelta('0 days 00:00:32'),
 Timedelta('0 days 00:00:39'),
 Timedelta('0 days 00:00:35'),
 Timedelta('0 days 00:00:27'),
 Timedelta('5 days 03:42:00'),
 Timedelta('0 days 00:00:45'),
 Timedelta('0 days 00:00:32'),
 Timedelta('8 days 00:22:41'),
 Timedelta('10 days 06:36:56'),
 Timedelta('0 days 00:00:25'),
 Timedelta('25 days 01:50:50'),
 Timedelta('0 days 00:00:41'),
 Timedelta('4 days 05:20:53'),
 Timedelta('0 days 00:00:28'),
 Timedelta('13 days 14:33:21'),
 Timedelta('7 days 04:43:41'),
 Timedelta('0 days 00:00:50'),
 Timedelta('8 days 21:19:36'),
 Timedelta('5 days 22:04:19'),
 Timedelta('0 days 00:00:49'),
 Timedelta('2 days 19:02:24'),
 Timedelta('15 days 20:31:03'),
 Timedelta('11 days 20:24:51'),
 Timedelta('11 days 17:35:08'),
 Timedelta('5 days 02:24:07'),
 Timedelta('6 days 00:39:05'),
 Timedelta('0 days 00:00:22'),
 Timedelta('9 days 23:45:41'),
 Timedelta('0 days 00:01:00'),
 Timedelta('5 days 02:57:13'),
 Timedelta('3 days 05:27:51'),
 Timedelta('0 days 00:00:35'),
 Timedelta('12 days 07:53:17'),
 Timedelta('8 days 05:56:28'),
 Timedelta('4 days 03:51:03'),
 Timedelta('0 days 00:00:25'),
 Timedelta('7 days 23:55:28'),
 Timedelta('0 days 00:01:00'),
 Timedelta('0 days 00:00:37'),
 Timedelta('4 days 00:02:13'),
 Timedelta('0 days 00:00:39'),
 Timedelta('5 days 08:04:40'),
 Timedelta('0 days 03:02:07'),
 Timedelta('10 days 02:11:02'),
 Timedelta('16 days 04:52:18'),
 Timedelta('12 days 06:02:16'),
 Timedelta('0 days 00:01:00'),
 Timedelta('7 days 23:18:38'),
 Timedelta('12 days 18:59:02'),
 Timedelta('10 days 04:35:29'),
 Timedelta('0 days 00:00:27'),
 Timedelta('5 days 06:48:59'),
 Timedelta('10 days 21:03:38'),
 Timedelta('7 days 21:24:36'),
 Timedelta('0 days 00:00:22'),
 Timedelta('16 days 01:26:48'),
 Timedelta('0 days 00:00:27'),
 Timedelta('11 days 02:33:47'),
 Timedelta('3 days 01:12:12'),
 Timedelta('0 days 00:00:27'),
 Timedelta('7 days 17:20:10'),
 Timedelta('4 days 21:45:02'),
 Timedelta('0 days 00:00:27'),
 Timedelta('4 days 08:44:00'),
 Timedelta('9 days 11:38:25'),
 Timedelta('0 days 00:00:38'),
 Timedelta('6 days 00:53:11'),
 Timedelta('9 days 06:48:07'),
 Timedelta('5 days 04:04:12'),
 Timedelta('0 days 00:01:00'),
 Timedelta('6 days 02:24:54'),
 Timedelta('0 days 00:00:32'),
 Timedelta('0 days 00:01:23'),
 Timedelta('1 days 19:56:24'),
 Timedelta('5 days 23:56:16'),
 Timedelta('5 days 06:07:55'),
 Timedelta('12 days 01:08:13'),
 Timedelta('0 days 00:00:25'),
 Timedelta('6 days 19:06:34'),
 Timedelta('0 days 00:00:47'),
 Timedelta('12 days 02:14:58'),
 Timedelta('14 days 12:37:34'),
 Timedelta('0 days 00:00:19'),
 Timedelta('4 days 03:08:17'),
 Timedelta('0 days 00:00:33'),
 Timedelta('3 days 02:49:27'),
 Timedelta('7 days 07:22:20'),
 Timedelta('5 days 20:20:14'),
 Timedelta('0 days 00:00:36'),
 Timedelta('4 days 02:39:37'),
 Timedelta('21 days 01:39:24'),
 Timedelta('2 days 00:48:55'),
 Timedelta('8 days 02:06:41'),
 Timedelta('3 days 00:09:14'),
 Timedelta('12 days 21:59:35'),
 Timedelta('0 days 00:00:32'),
 Timedelta('13 days 04:04:05'),
 Timedelta('0 days 00:00:33'),
 Timedelta('0 days 00:02:01'),
 Timedelta('0 days 00:00:21'),
 Timedelta('3 days 23:37:05'),
 Timedelta('23 days 23:15:42'),
 Timedelta('0 days 00:00:33'),
 Timedelta('6 days 02:00:09'),
 Timedelta('0 days 00:00:30'),
 Timedelta('0 days 00:00:49'),
 Timedelta('16 days 21:38:12'),
 Timedelta('0 days 00:00:37'),
 Timedelta('4 days 04:01:07'),
 Timedelta('7 days 07:16:13'),
 Timedelta('7 days 23:44:52'),
 Timedelta('9 days 06:34:13'),
 Timedelta('5 days 21:39:06'),
 Timedelta('4 days 03:43:48'),
 Timedelta('5 days 06:32:23'),
 Timedelta('8 days 00:04:48'),
 Timedelta('2 days 00:44:01'),
 Timedelta('14 days 20:23:47'),
 Timedelta('4 days 20:03:22'),
 Timedelta('13 days 20:18:38'),
 Timedelta('6 days 22:49:41'),
 Timedelta('0 days 00:00:38'),
 Timedelta('12 days 18:52:03'),
 Timedelta('12 days 19:12:38'),
 Timedelta('0 days 00:00:36'),
 Timedelta('7 days 06:50:03'),
 Timedelta('0 days 00:00:29'),
 Timedelta('14 days 21:56:56'),
 Timedelta('8 days 03:07:49'),
 Timedelta('6 days 07:24:32'),
 Timedelta('8 days 12:02:09'),
 Timedelta('0 days 00:00:27'),
 Timedelta('4 days 17:51:15'),
 Timedelta('5 days 05:35:12'),
 Timedelta('11 days 22:05:03'),
 Timedelta('10 days 23:28:24'),
 Timedelta('0 days 00:00:26'),
 Timedelta('20 days 03:48:47'),
 Timedelta('24 days 03:27:47'),
 Timedelta('0 days 00:00:58'),
 Timedelta('0 days 00:00:39'),
 Timedelta('9 days 04:58:26'),
 Timedelta('5 days 23:54:54'),
 Timedelta('0 days 00:00:41'),
 Timedelta('41 days 05:34:02'),
 Timedelta('0 days 00:00:27'),
 Timedelta('10 days 23:57:14'),
 Timedelta('0 days 00:00:29'),
 Timedelta('22 days 01:16:01'),
 Timedelta('11 days 22:00:47'),
 Timedelta('17 days 00:45:00'),
 Timedelta('0 days 00:00:27'),
 Timedelta('6 days 03:33:11'),
 Timedelta('7 days 22:17:54'),
 Timedelta('15 days 04:44:06'),
 Timedelta('11 days 01:00:58'),
 Timedelta('21 days 01:39:22'),
 Timedelta('0 days 00:00:36'),
 Timedelta('0 days 00:00:28'),
 Timedelta('6 days 01:40:26'),
 Timedelta('0 days 00:01:00'),
 Timedelta('7 days 02:14:30'),
 Timedelta('0 days 00:00:22'),
 Timedelta('14 days 04:53:37'),
 Timedelta('9 days 03:01:50'),
 Timedelta('13 days 06:05:32'),
 Timedelta('0 days 00:00:26'),
 Timedelta('0 days 00:00:45'),
 Timedelta('30 days 17:55:16'),
 Timedelta('15 days 01:54:46'),
 Timedelta('0 days 00:01:03'),
 Timedelta('5 days 21:39:53'),
 Timedelta('0 days 00:00:43'),
 Timedelta('0 days 00:00:27'),
 Timedelta('0 days 00:00:37'),
 Timedelta('2 days 02:50:20'),
 Timedelta('10 days 05:20:28'),
 Timedelta('7 days 04:14:53'),
 Timedelta('0 days 00:01:06'),
 Timedelta('0 days 00:01:09'),
 Timedelta('5 days 00:48:35'),
 Timedelta('0 days 00:00:38'),
 Timedelta('12 days 01:17:29'),
 Timedelta('2 days 22:08:05'),
 Timedelta('0 days 00:00:37'),
 Timedelta('16 days 02:37:50'),
 Timedelta('15 days 20:38:29'),
 Timedelta('9 days 01:43:56'),
 Timedelta('0 days 00:00:21'),
 Timedelta('14 days 23:56:14'),
 Timedelta('0 days 00:00:22'),
 Timedelta('10 days 20:15:35'),
 Timedelta('0 days 00:00:48'),
 Timedelta('13 days 20:57:25'),
 Timedelta('0 days 00:00:27'),
 Timedelta('0 days 00:00:23'),
 Timedelta('7 days 03:32:28'),
 Timedelta('4 days 05:52:20'),
 Timedelta('9 days 22:08:37'),
 Timedelta('0 days 00:00:35'),
 Timedelta('3 days 00:25:21'),
 Timedelta('0 days 00:00:25'),
 Timedelta('12 days 05:29:20'),
 Timedelta('3 days 00:08:53'),
 Timedelta('13 days 00:58:55'),
 Timedelta('0 days 00:00:42'),
 Timedelta('0 days 00:00:24'),
 Timedelta('13 days 02:35:36'),
 Timedelta('0 days 00:00:28'),
 Timedelta('8 days 02:23:45'),
 Timedelta('0 days 00:00:38'),
 Timedelta('0 days 00:00:22'),
 Timedelta('9 days 00:19:25'),
 Timedelta('0 days 00:00:46'),
 Timedelta('0 days 00:00:26'),
 Timedelta('0 days 00:00:35'),
 Timedelta('16 days 07:14:18'),
 Timedelta('22 days 02:57:36'),
 Timedelta('9 days 01:51:04'),
 Timedelta('11 days 04:00:41'),
 Timedelta('0 days 00:00:36'),
 Timedelta('0 days 00:00:26'),
 Timedelta('5 days 21:37:40'),
 Timedelta('3 days 22:24:23'),
 Timedelta('0 days 00:00:54'),
 Timedelta('0 days 00:00:29'),
 Timedelta('16 days 23:19:40'),
 Timedelta('0 days 00:00:19'),
 Timedelta('0 days 00:00:52'),
 Timedelta('11 days 05:06:31'),
 Timedelta('11 days 03:54:30'),
 Timedelta('21 days 00:42:46'),
 Timedelta('5 days 22:26:46'),
 Timedelta('0 days 00:00:28'),
 Timedelta('0 days 00:00:30'),
 Timedelta('12 days 05:20:53'),
 Timedelta('0 days 00:00:19'),
 Timedelta('0 days 00:00:32'),
 Timedelta('7 days 00:22:30'),
 Timedelta('0 days 00:00:32'),
 Timedelta('6 days 05:39:52'),
 Timedelta('0 days 00:00:39'),
 Timedelta('10 days 00:30:07'),
 Timedelta('0 days 00:00:37'),
 Timedelta('0 days 00:00:51'),
 Timedelta('3 days 03:21:30'),
 Timedelta('8 days 04:14:41'),
 Timedelta('4 days 04:20:46'),
 Timedelta('5 days 00:22:59'),
 Timedelta('0 days 00:00:30'),
 Timedelta('0 days 00:03:53'),
 Timedelta('4 days 03:35:48'),
 Timedelta('4 days 22:55:21'),
 Timedelta('0 days 00:00:35'),
 Timedelta('14 days 00:07:33'),
 Timedelta('3 days 07:28:27'),
 Timedelta('11 days 00:15:20'),
 Timedelta('0 days 00:00:37'),
 Timedelta('5 days 00:24:46'),
 Timedelta('7 days 03:05:13'),
 Timedelta('0 days 00:00:32'),
 Timedelta('0 days 00:00:41'),
 Timedelta('35 days 01:03:57'),
 Timedelta('5 days 19:37:17'),
 Timedelta('0 days 00:00:31'),
 Timedelta('6 days 16:34:12'),
 Timedelta('30 days 04:47:21'),
 Timedelta('5 days 03:13:04'),
 Timedelta('7 days 06:43:52'),
 Timedelta('10 days 03:10:07'),
 Timedelta('3 days 03:34:32'),
 Timedelta('2 days 02:10:20'),
 Timedelta('0 days 00:00:33'),
 Timedelta('0 days 00:00:29'),
 Timedelta('10 days 04:20:29'),
 Timedelta('17 days 22:29:33'),
 Timedelta('10 days 00:23:57'),
 Timedelta('0 days 00:00:21'),
 Timedelta('6 days 18:00:53'),
 Timedelta('0 days 00:00:25'),
 Timedelta('0 days 00:00:28'),
 Timedelta('3 days 06:07:35'),
 Timedelta('8 days 06:48:10'),
 Timedelta('18 days 02:03:47'),
 Timedelta('3 days 22:05:25'),
 Timedelta('8 days 20:15:32'),
 Timedelta('8 days 01:31:03'),
 Timedelta('4 days 23:50:34'),
 Timedelta('0 days 00:00:34'),
 Timedelta('17 days 02:44:00'),
 Timedelta('8 days 21:03:23'),
 Timedelta('0 days 16:30:24'),
 Timedelta('0 days 00:00:30'),
 Timedelta('0 days 00:00:37'),
 Timedelta('36 days 06:41:03'),
 Timedelta('2 days 04:27:10'),
 Timedelta('10 days 07:35:40'),
 Timedelta('4 days 12:12:43'),
 Timedelta('0 days 00:00:47'),
 Timedelta('0 days 00:00:17'),
 Timedelta('15 days 07:31:04'),
 Timedelta('20 days 02:20:15'),
 Timedelta('0 days 00:00:25'),
 Timedelta('0 days 00:00:31'),
 Timedelta('7 days 10:30:28'),
 Timedelta('3 days 22:55:24'),
 Timedelta('7 days 07:13:28'),
 Timedelta('14 days 18:25:56'),
 Timedelta('0 days 00:00:24'),
 Timedelta('1 days 05:45:09'),
 Timedelta('6 days 01:38:17'),
 Timedelta('0 days 00:00:33'),
 Timedelta('7 days 04:00:58'),
 Timedelta('0 days 00:00:28'),
 Timedelta('0 days 00:00:40'),
 Timedelta('6 days 00:27:16'),
 Timedelta('4 days 01:10:23'),
 Timedelta('7 days 06:32:20'),
 Timedelta('0 days 00:00:45'),
 Timedelta('5 days 18:59:22'),
 Timedelta('47 days 05:06:24'),
 Timedelta('18 days 05:18:11'),
 Timedelta('15 days 01:50:34'),
 Timedelta('0 days 00:00:29'),
 Timedelta('5 days 06:02:38'),
 Timedelta('0 days 00:00:48'),
 Timedelta('11 days 06:20:44'),
 Timedelta('4 days 00:31:29'),
 Timedelta('0 days 00:00:33'),
 Timedelta('14 days 16:30:31'),
 Timedelta('12 days 03:41:15'),
 Timedelta('6 days 22:47:38'),
 Timedelta('19 days 21:45:25'),
 Timedelta('10 days 21:49:41'),
 Timedelta('17 days 06:34:46'),
 Timedelta('0 days 00:00:40'),
 Timedelta('28 days 23:27:39'),
 Timedelta('4 days 08:23:14'),
 Timedelta('7 days 00:27:04'),
 Timedelta('0 days 00:00:43'),
 Timedelta('19 days 04:53:05'),
 Timedelta('4 days 09:25:28'),
 Timedelta('0 days 21:10:40'),
 Timedelta('0 days 00:00:25'),
 Timedelta('6 days 23:20:06'),
 Timedelta('5 days 13:16:12'),
 Timedelta('0 days 00:00:37'),
 Timedelta('7 days 02:43:02'),
 Timedelta('12 days 00:11:50'),
 Timedelta('9 days 02:02:09'),
 Timedelta('15 days 17:48:54'),
 Timedelta('4 days 00:09:24'),
 Timedelta('0 days 00:00:27'),
 Timedelta('0 days 00:00:30'),
 Timedelta('12 days 01:08:38'),
 Timedelta('11 days 00:12:53'),
 Timedelta('11 days 22:03:38'),
 Timedelta('0 days 00:00:37'),
 Timedelta('6 days 02:08:34'),
 Timedelta('13 days 06:35:04'),
 Timedelta('3 days 23:08:19'),
 Timedelta('0 days 00:00:25'),
 Timedelta('9 days 22:20:17'),
 Timedelta('6 days 00:21:12'),
 Timedelta('0 days 00:00:31'),
 Timedelta('0 days 00:01:09'),
 Timedelta('2 days 04:52:25'),
 Timedelta('4 days 23:03:59'),
 Timedelta('0 days 00:00:28'),
 Timedelta('13 days 03:20:16'),
 Timedelta('8 days 22:37:01'),
 Timedelta('8 days 08:30:19'),
 Timedelta('12 days 03:13:08'),
 Timedelta('3 days 00:01:20'),
 Timedelta('0 days 00:00:31'),
 Timedelta('0 days 00:00:32'),
 Timedelta('3 days 07:10:58'),
 Timedelta('3 days 21:48:01'),
 Timedelta('2 days 21:41:54'),
 Timedelta('16 days 21:47:35'),
 Timedelta('0 days 00:00:22'),
 Timedelta('0 days 00:00:30'),
 Timedelta('0 days 00:00:38'),
 Timedelta('6 days 01:59:32'),
 Timedelta('24 days 04:08:44'),
 Timedelta('0 days 00:00:33'),
 Timedelta('0 days 00:00:41'),
 Timedelta('0 days 00:00:31'),
 Timedelta('4 days 21:31:03'),
 Timedelta('2 days 03:37:55'),
 Timedelta('8 days 03:17:03'),
 Timedelta('0 days 00:00:34'),
 Timedelta('0 days 00:00:32'),
 Timedelta('4 days 21:48:02'),
 Timedelta('0 days 00:00:28'),
 Timedelta('11 days 10:22:33'),
 Timedelta('0 days 00:00:38'),
 Timedelta('0 days 00:00:28'),
 Timedelta('0 days 00:00:27'),
 Timedelta('0 days 00:00:25'),
 Timedelta('12 days 02:49:08'),
 Timedelta('4 days 00:14:53'),
 Timedelta('0 days 00:00:29'),
 Timedelta('0 days 00:00:29'),
 Timedelta('5 days 08:40:55'),
 Timedelta('10 days 06:27:58'),
 Timedelta('6 days 17:13:17'),
 Timedelta('21 days 18:16:51'),
 Timedelta('4 days 12:14:07'),
 Timedelta('10 days 06:17:01'),
 Timedelta('3 days 03:42:39'),
 Timedelta('6 days 23:01:13'),
 Timedelta('24 days 08:51:32'),
 Timedelta('10 days 22:38:14'),
 Timedelta('0 days 00:00:30'),
 Timedelta('0 days 00:00:24'),
 Timedelta('4 days 01:09:40'),
 Timedelta('3 days 04:20:00'),
 Timedelta('25 days 03:58:14'),
 Timedelta('0 days 00:00:35'),
 Timedelta('0 days 00:00:52'),
 Timedelta('0 days 00:00:33'),
 Timedelta('0 days 00:00:38'),
 Timedelta('0 days 00:00:44'),
 Timedelta('6 days 00:56:55'),
 Timedelta('8 days 05:10:51'),
 Timedelta('5 days 07:01:49'),
 Timedelta('7 days 23:22:44'),
 Timedelta('10 days 02:43:03'),
 Timedelta('12 days 01:53:21'),
 Timedelta('13 days 07:41:43'),
 Timedelta('9 days 02:39:26'),
 Timedelta('7 days 02:22:58'),
 Timedelta('4 days 01:41:23'),
 Timedelta('3 days 03:29:04'),
 Timedelta('7 days 23:07:20'),
 Timedelta('7 days 23:12:43'),
 Timedelta('0 days 00:00:29'),
 Timedelta('13 days 02:22:22'),
 Timedelta('0 days 00:00:32'),
 Timedelta('29 days 04:17:22'),
 Timedelta('0 days 00:00:39'),
 Timedelta('0 days 00:01:18'),
 Timedelta('0 days 00:01:04'),
 Timedelta('0 days 00:00:37'),
 Timedelta('6 days 23:49:38'),
 Timedelta('6 days 22:09:39'),
 Timedelta('0 days 00:03:17'),
 Timedelta('21 days 02:44:29'),
 Timedelta('0 days 00:00:37'),
 Timedelta('0 days 00:00:24'),
 Timedelta('0 days 00:00:25'),
 Timedelta('4 days 06:00:51'),
 Timedelta('9 days 00:11:51'),
 Timedelta('6 days 02:42:12'),
 Timedelta('8 days 00:39:05'),
 Timedelta('19 days 01:16:40'),
 Timedelta('0 days 00:00:28'),
 Timedelta('20 days 22:39:11'),
 Timedelta('6 days 02:27:08'),
 Timedelta('0 days 00:00:33'),
 Timedelta('0 days 00:00:27'),
 Timedelta('9 days 20:42:59'),
 Timedelta('19 days 03:54:56'),
 Timedelta('0 days 00:00:28'),
 Timedelta('3 days 02:31:02'),
 Timedelta('8 days 04:15:18'),
 Timedelta('3 days 03:24:25'),
 Timedelta('0 days 00:00:59'),
 Timedelta('0 days 00:00:31'),
 Timedelta('18 days 23:47:48'),
 Timedelta('0 days 00:03:27'),
 Timedelta('5 days 05:21:00'),
 Timedelta('6 days 03:13:08'),
 Timedelta('20 days 00:48:54'),
 Timedelta('0 days 00:00:58'),
 Timedelta('7 days 00:11:27'),
 Timedelta('0 days 00:00:33'),
 Timedelta('7 days 04:13:31'),
 Timedelta('17 days 04:07:30'),
 Timedelta('0 days 00:00:32'),
 Timedelta('14 days 04:00:42'),
 Timedelta('0 days 00:00:32'),
 Timedelta('9 days 00:35:28'),
 Timedelta('6 days 04:53:49'),
 Timedelta('11 days 23:47:58'),
 Timedelta('0 days 00:00:24'),
 Timedelta('3 days 21:20:37'),
 Timedelta('7 days 03:27:01'),
 Timedelta('0 days 00:00:31'),
 Timedelta('2 days 20:44:05'),
 Timedelta('6 days 23:29:20'),
 Timedelta('0 days 00:00:48'),
 Timedelta('8 days 05:03:25'),
 Timedelta('7 days 22:52:01'),
 Timedelta('7 days 08:46:43'),
 Timedelta('9 days 23:15:04'),
 Timedelta('19 days 04:00:25'),
 Timedelta('10 days 23:36:07'),
 Timedelta('0 days 00:00:35'),
 Timedelta('6 days 04:29:06'),
 Timedelta('13 days 04:39:21'),
 Timedelta('26 days 14:33:59'),
 Timedelta('7 days 03:34:36'),
 Timedelta('0 days 00:01:09'),
 Timedelta('12 days 10:05:20'),
 Timedelta('0 days 00:00:22'),
 Timedelta('0 days 00:00:40'),
 Timedelta('0 days 00:00:29'),
 Timedelta('0 days 00:00:25'),
 Timedelta('5 days 18:54:00'),
 Timedelta('9 days 23:23:48'),
 Timedelta('10 days 23:07:30'),
 Timedelta('0 days 00:00:45'),
 Timedelta('0 days 00:00:28'),

In [9]:
parthner_array = df_new[df_new['result_name'] == 'Принят']['id_applicant'].unique() # время найма по заявкам
tth = pd.DataFrame(columns=('Обработка', 'Интервью с руководителем', 'СБ', 'Оформление'))
for i in parthner_array:
    parthner = df_new[df_new['id_applicant'] == i]
    
    if len(parthner[parthner['stage_name'] == 'Обработка']['action_date'])!=0:
        treatment = max(parthner[parthner['stage_name'] == 'Обработка']['action_date']) - min(parthner[parthner['stage_name'] == 'Создание кандидата']['action_date'])
    else:
        treatment = None
        
    if len(parthner[parthner['stage_name'] == 'Интервью с руководителем']['action_date'])!=0:
        interview = max(parthner[parthner['stage_name'] == 'Интервью с руководителем']['action_date'])- min(parthner[parthner['stage_name'] == 'Интервью с руководителем']['action_date'])
    else:
        interview = None
        
    if len(parthner[parthner['stage_name'] == 'СБ']['action_date'])!=0:
        secServ = max(parthner[parthner['stage_name'] == 'СБ']['action_date'])- min(parthner[parthner['stage_name'] == 'СБ']['action_date'])
    else:
        secServ = None
        
    if len(parthner[parthner['stage_name'] == 'Оформление']['action_date'])!=0:
        registration = max(parthner[(parthner['stage_name'] == 'Оформление') & (parthner['result_name'] == 'Принят')]['action_date'])- min(parthner[parthner['stage_name'] == 'Оформление']['action_date'])
    else:
        registration = None
        
    tth.loc[i] = [treatment, interview, secServ, registration]
tth

,Обработка,Интервью с руководителем,СБ,Оформление
4845101,0 days 00:00:23,0 days 00:00:01,0 days 18:14:47,4 days 04:50:53
4880681,0 days 00:00:29,0 days 00:00:02,0 days 00:00:04,0 days 00:00:11
4786590,NaT,NaT,NaT,4 days 21:28:57
4838086,0 days 00:00:19,0 days 00:00:02,0 days 02:10:47,5 days 04:12:02
4808982,0 days 00:03:15,0 days 00:00:00,0 days 00:00:01,0 days 00:01:03
...,...,...,...,...
4870239,0 days 00:00:21,0 days 00:00:01,0 days 12:13:33,3 days 00:07:12
4883604,0 days 00:00:11,0 days 00:00:01,0 days 00:00:01,0 days 00:00:04
4870328,0 days 00:00:17,0 days 00:00:00,0 days 02:11:20,3 days 02:49:44
4870452,0 days 00:00:50,0 days 00:00:01,0 days 01:05:45,3 days 03:33:04
4883517,0 days 00:00:10,0 days 00:00:00,0 days 00:00:01,0 days 00:00:04

In [ ]:
tth[tth['Оформление']=='19 days 18:04:01']

In [10]:
tth.describe()

,Обработка,Интервью с руководителем,СБ,Оформление
count,4955,5057,5111,7042
mean,0 days 00:10:42.293642785,0 days 05:08:36.326675894,0 days 04:50:36.113285071,2 days 19:34:18.999431979
std,0 days 05:45:33.721710957,0 days 23:40:04.512646033,0 days 10:31:22.040426009,3 days 16:16:15.598436796
min,0 days 00:00:05,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
25%,0 days 00:00:15,0 days 00:00:01,0 days 00:00:02,0 days 00:00:06
50%,0 days 00:00:19,0 days 00:00:01,0 days 00:00:03,0 days 22:35:18
75%,0 days 00:00:26,0 days 00:00:01,0 days 02:38:36,4 days 23:53:28.500000
max,13 days 02:26:54,14 days 05:49:54,11 days 06:46:49,19 days 18:04:01

In [11]:
tth[tth['Оформление']=='19 days 18:04:01']

        Обработка Интервью с руководителем  СБ       Оформление
4767626       NaT                      NaT NaT 19 days 18:04:01

In [12]:
df_new[df_new['id_applicant'] == 4828639] # самая большая обработка
df_new[df_new['id_applicant'] == 4815822] # самая большое Интервью с руководителем
df_new[df_new['id_applicant'] == 4811887] # самая большая проверка СБ
df_new[df_new['id_applicant'] == 4767626] # самая большое Оформление

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name,position_name,is_active_action,is_open_action
185059,4767626,3832421,-1,49449,2020-03-16 16:13:11,Создание кандидата,NaN,NaN,Продавец-кассир,True,False
299594,4767626,3832421,26637097,49449,2020-03-25 16:55:10,Оформление,Узнать результаты приема,Перенос звонка,Продавец-кассир,True,False
299593,4767626,3832421,27105428,49449,2020-04-14 10:59:11,Оформление,Узнать результаты приема,Принят,Продавец-кассир,True,False

In [13]:
df_new[df_new['id_applicant'] == 4767626] # самая большое Оформление

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name,position_name,is_active_action,is_open_action
185059,4767626,3832421,-1,49449,2020-03-16 16:13:11,Создание кандидата,NaN,NaN,Продавец-кассир,True,False
299594,4767626,3832421,26637097,49449,2020-03-25 16:55:10,Оформление,Узнать результаты приема,Перенос звонка,Продавец-кассир,True,False
299593,4767626,3832421,27105428,49449,2020-04-14 10:59:11,Оформление,Узнать результаты приема,Принят,Продавец-кассир,True,False

In [14]:
parthner = df_new[df_new['id_applicant'] == parthner_array[0]]
len(parthner[parthner['stage_name'] == 'Обработка']['action_date'])
treatment = max(parthner[parthner['stage_name'] == 'Оформление']['action_date']) - min(parthner[parthner['stage_name'] == 'Оформление']['action_date'])
treatment
parthner[(parthner['stage_name'] == 'Оформление') & (parthner['result_name'] == 'Принят')]['action_date']

221836   2020-04-13 16:28:35
Name: action_date, dtype: datetime64[ns]

In [15]:
er = df_new[df_new['id_applicant'] == 4845101]
er1 = max(er[er['stage_name'] == 'Обработка']['action_date'])- min(er[er['stage_name'] == 'Создание кандидата']['action_date'])
print(er1)
er2 = max(er[er['stage_name'] == 'Интервью с руководителем']['action_date'])- min(er[er['stage_name'] == 'Интервью с руководителем']['action_date'])
print(er2)
er3 = max(er[er['stage_name'] == 'СБ']['action_date'])- min(er[er['stage_name'] == 'СБ']['action_date'])
print(er3)
er4 = max(er[er['stage_name'] == 'Оформление']['action_date'])- min(er[er['stage_name'] == 'Оформление']['action_date'])
print(er4)

df_er = pd.DataFrame(columns=('Обработка', 'Интервью с руководителем', 'СБ', 'Оформление'))
df_er.loc['4845101'] = [er1,er2,er3,er4]
df_er

0 days 00:00:23
0 days 00:00:01
0 days 18:14:47
4 days 04:50:53

,Обработка,Интервью с руководителем,СБ,Оформление
4845101,0 days 00:00:23,0 days 00:00:01,0 days 18:14:47,4 days 04:50:53

In [16]:
er

,id_applicant,id_partner,id_log,department_id,action_date,stage_name,activity_name,result_name,position_name,is_active_action,is_open_action
183461,4845101,537513,-1,31453,2020-04-04 16:16:11,Создание кандидата,NaN,NaN,Продавец-кассир,True,False
221901,4845101,537513,26864946,31453,2020-04-04 16:16:32,Обработка,Провести первичную обработку,Подходит,Продавец-кассир,True,False
221900,4845101,537513,26864948,31453,2020-04-04 16:16:34,Обработка,Проверка формы обращения,Не резерв,Продавец-кассир,True,False
221899,4845101,537513,26864949,31453,2020-04-04 16:16:35,Интервью с руководителем,Назначить интервью с руководителем,Встреча назначена,Продавец-кассир,True,False
221898,4845101,537513,26864950,31453,2020-04-04 16:16:36,Интервью с руководителем,Узнать результаты интервью с руководителем,Подходит,Продавец-кассир,True,False
221897,4845101,537513,26864952,31453,2020-04-04 16:16:37,СБ,Подготовить анкету кандидата,Подготовлена,Продавец-кассир,True,False
221895,4845101,537513,26869588,31453,2020-04-05 10:31:23,СБ,Узнать результаты СБ,Подходит,Продавец-кассир,True,False
221896,4845101,537513,26869589,31453,2020-04-05 10:31:24,СБ,Проверка формы обращения,Не резерв,Продавец-кассир,True,False
221894,4845101,537513,26984718,31453,2020-04-09 11:37:42,Оформление,Назначить время на оформление,Недозвон,Продавец-кассир,True,False
221893,4845101,537513,27013678,31453,2020-04-10 09:59:12,Оформление,Назначить время на оформление,Время назначено,Продавец-кассир,True,False
221892,4845101,537513,27013682,31453,2020-04-10 09:59:15,Оформление,Узнать результаты приема,Нет обратной связи от руководителя,Продавец-кассир,True,False
221891,4845101,537513,27025016,31453,2020-04-10 14:00:02,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем,Продавец-кассир,True,False
221890,4845101,537513,27069555,31453,2020-04-13 09:00:48,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем,Продавец-кассир,True,False
221889,4845101,537513,27091776,31453,2020-04-13 16:18:20,Оформление,Предоставить обратную связь по кандидату,ОС не предоставлена руководителем,Продавец-кассир,True,False
221888,4845101,537513,27092386,31453,2020-04-13 16:28:03,Оформление,Предоставить обратную связь по кандидату,ОС предоставлена руководителем,Продавец-кассир,True,False
221836,4845101,537513,27092407,31453,2020-04-13 16:28:35,Оформление,Узнать результаты приема,Принят,Продавец-кассир,True,False

In [17]:
tthDays=[]
for i in tth:
    tthDays.append(i.days)

AttributeError: 'str' object has no attribute 'days'

In [ ]:
import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(10,5))
ax.hist(tthDays, bins = 30)
ax.plot()

In [ ]:
er = []
for i in tthDays:
    if (i < 30) and (i != 0):
        er.append(i)
fig, ax = plt.subplots(figsize=(10,5))
ax.hist(er, bins = 29)
ax.plot()

In [ ]:
er = pd.DataFrame(tthDays,columns =['Days'])
er.describe()

In [ ]:
df_new[df_new['result_name'] == 'Принят']['id_applicant'].unique()

In [ ]:
stage_name=[]
for i in df_new[df_new['result_name'] == 'Принят']['id_applicant']:
    er = df_new[df_new['id_applicant'] == i]['stage_name'].unique()
    for b in er:
        if b not in stage_name:
            stage_name.append(b)
stage_name

In [ ]:
er = df_new[(df_new['stage_name'] == 'Выход на работу')]['id_applicant']
qwe = []
for i in df_new[(df_new['stage_name'] == 'Выход на работу')]['id_applicant']:
    er = df_new[df_new['id_applicant'] == i]
    if len(er[er['result_name'] == 'Принят']) !=0:
        qwe.append(er['id_applicant'].unique())
        
qwe

In [ ]:
df_new[df_new['id_applicant'] == 4824789]

In [ ]:
er = df_new[df_new['id_applicant'] == 4845101]
max(er['action_date'])-min(er['action_date'])
er

In [ ]:
er = df_new[df_new['id_applicant'] == 4845101]
#er[(er['result_name'] == 'Принят') & (er['activity_name'] == 'Узнать результаты приема') &(er['stage_name'] == 'Оформление')]
er

In [ ]:
df_new[df_new['result_name'] == 'Принят']

In [ ]:
print(df_new[df_new['result_name']=='Принят']['activity_name'].unique())
print(df_new[df_new['result_name']=='Принят']['stage_name'].unique())

In [ ]:
max(ert['action_date'])-min(ert['action_date'])

In [ ]:
df.columns

In [ ]:
df = df.drop(['position_name'], axis =1)

In [ ]:
df['is_active_action'].value_counts()

In [ ]:
#Понятия не имею нахера тут столбец is_active_action если у него все значения тру
df = df.drop(['is_active_action'], axis =1)

In [ ]:
df = df.sort_values(by = ['id_partner', 'action_date']) #отсортируем данные по кандидату и дате действия 
sorted_df = df.copy()
df

In [ ]:
df['is_open_action'].value_counts()

In [ ]:
df['stage_name'].unique()

In [ ]:
a = (['Создание кандидата', 'Интервью с руководителем', 'СБ', #Список стадий 2018
       'Обработка', 'Назначение времени на оформление/медосмотр',
       'Оформление', 'Смена вакансии', 'Выход на работу', 'Отказался',
       'Резерв', 'Ожидание', 'Не прошел СБ', 'Мы отказали',
       'Черный список', 'Кадровый резерв'])

In [ ]:
b = (['Создание кандидата', 'Интервью с руководителем', 'Обработка', #список стадий 2020
       'Оформление', 'Смена вакансии', 'СБ', 'Не прошел СБ',
       'Мы отказали', 'Выход на работу', 'Отказался', 'Резерв',
       'Черный список'])

In [ ]:
print('стадии что не вошли в 2020')
print('--------------')
i = 0
while i < 15:
    if (a[i] not in b):  
        print(a[i])
    i = i + 1

In [ ]:
print('стадии который нет в 2018, но есть в 2020')
print('--------------')
i = 0
while i < 12:
    if (b[i] not in a):  
        print(b[i])
    i = i + 1

In [ ]:
sorted_df['result_name'].value_counts()

In [ ]:
sorted_df['stage_name'].value_counts()

In [ ]:
df[df['result_name'] == 'Принят']

In [ ]:
data[(data['position_name'] == 'Продавец-кассир') &  (data['stage_name'] == 'Оформление')]['activity_name'].unique()

In [ ]:
df[(df['stage_name'] == 'Обработка') & (df['activity_name'] == 'Провести первичную обработку') & (df['result_name'] == 'Подходит')]

In [ ]:
df[df['id_applicant'] == 4519604]

In [ ]:
len(df['id_applicant'].unique())

In [ ]:
df[df['id_applicant'] == 4886560]

In [ ]:
df[(df['stage_name'] == 'Интервью с руководителем') & (df['result_name'] == 'Недозвон')]

In [ ]:
df[df['id_applicant'] == 4530625]

In [ ]:
df[df['id_applicant'] == 4578838]

In [ ]:
df[df['result_name'] == 'Не подходит']

In [ ]:
df[df['id_applicant'] == 4508429]

In [ ]:
df[(df['stage_name'] == 'Оформление') & (df['activity_name'] == 'Назначить время на оформление')]

In [ ]:
df[(df['stage_name'] == 'Оформление') & (df['activity_name'] == 'Предоставить обратную связь по кандидату') & (df['result_name'] == 'ОС не предоставлена руководителем')].head(50)

In [ ]:
df[df['id_applicant'] == 4596351]

In [ ]:
df[df['id_applicant'] == 4604049]

In [ ]:
df[df['result_name'] == 'Черный список']

In [ ]:
df[df['id_applicant'] == 4790505]

In [ ]:
df[df['stage_name' == 'Оформление']]['activity_name'].unique()

Классно получается, у нас стадии этапы найма одного человека записываются полность, а другого заносят в систему только на создание и оформление, данные не все ---> Система не проверяет предыдущие этапы и даёт запись сразу на последний этап(подразумеваю что так не должно работать)

1) Стадия 'Создание кандидата'

Полный аналог 2018

In [ ]:
le_masque = df['stage_name'] == 'Создание кандидата'
df_create = df[le_masque]
df_create['activity_name'].unique()

2) Стадия 'Обработак' 

Обратить внимание, что у Ани 6 активностей на обработку, а в 2020 только две

Да и разновидности вариантов активностей в 2018 году было больше

In [ ]:
le_masque = df['stage_name'] == 'Обработка'
df_inter = df[le_masque]
df_inter['activity_name'].unique()

In [ ]:
le_masque = df['stage_name'] == 'Обработка'
le_masque &= df['activity_name'] == 'Провести первичную обработку'
df_inter_2 = df[le_masque]
df_inter_2['result_name'].unique()

In [ ]:
le_masque = df['stage_name'] == 'Обработка'
le_masque &= df['activity_name'] == 'Проверка формы обращения'
df_inter_2 = df[le_masque]
df_inter_2['result_name'].unique()

3) 'Интервью с руководителем'

Полный аналог активнойстей с 2018

Но по разновидностям вариантов активностей снова меньше чем в 2018

In [ ]:
le_masque = df['stage_name'] == 'Интервью с руководителем'
df_inter = df[le_masque]
df_inter['activity_name'].unique()

In [ ]:
le_masque = df['stage_name'] == 'Интервью с руководителем'
le_masque &= df['activity_name'] == 'Назначить интервью с руководителем'
df_inter_2 = df[le_masque]
df_inter_2['result_name'].unique()

In [ ]:
le_masque = df['stage_name'] == 'Интервью с руководителем'
le_masque &= df['activity_name'] == 'Узнать результаты интервью с руководителем'
df_inter_2 = df[le_masque]
df_inter_2['result_name'].unique()

In [ ]:
le_masque = df['stage_name'] == 'Интервью с руководителем'
le_masque &= df['activity_name'] == 'Предоставить обратную связь по кандидату'
df_inter_2 = df[le_masque]
df_inter_2['result_name'].unique()

4) Оформление

In [ ]:
le_masque = df['stage_name'] == 'Оформление'
df_inter = df[le_masque]
df_inter['activity_name'].unique()

In [ ]:
le_masque = df['stage_name'] == 'Оформление'
le_masque &= df['activity_name'] == 'Назначить время на оформление'
df_inter_2 = df[le_masque]
df_inter_2['result_name'].unique()

In [ ]:
le_masque = df['stage_name'] == 'Оформление'
le_masque &= df['activity_name'] == 'Узнать результаты приема'
df_inter_2 = df[le_masque]
df_inter_2['result_name'].unique()

In [ ]:
le_masque = df['stage_name'] == 'Оформление'
le_masque &= df['activity_name'] == 'Предоставить обратную связь по кандидату'
df_inter_2 = df[le_masque]
df_inter_2['result_name'].unique()

5) СБ 

Активностей в 2018 снова больше

In [ ]:
le_masque = df['stage_name'] == 'СБ'
df_inter = df[le_masque]
df_inter['activity_name'].unique()

In [ ]:
le_masque = df['stage_name'] == 'СБ'
le_masque &= df['activity_name'] == 'Подготовить анкету кандидата'
df_inter_2 = df[le_masque]
df_inter_2['result_name'].unique()

In [ ]:
le_masque = df['stage_name'] == 'СБ'
le_masque &= df['activity_name'] == 'Узнать результаты СБ'
df_inter_2 = df[le_masque]
df_inter_2['result_name'].unique()

In [ ]:
le_masque = df['stage_name'] == 'СБ'
le_masque &= df['activity_name'] == 'Проверка формы обращения'
df_inter_2 = df[le_masque]
df_inter_2['result_name'].unique()

6)Смена вакансии  

Ну хоть где-то аналог с 2018 XD

In [ ]:
le_masque = df['stage_name'] == 'Смена вакансии'
df_inter = df[le_masque]
df_inter['activity_name'].unique()

7)Не прошел СБ

In [ ]:
le_masque = df['stage_name'] == 'Не прошел СБ'
df_inter = df[le_masque]
df_inter['activity_name'].unique()

In [ ]:
le_masque = df['stage_name'] == 'Не прошел СБ'
le_masque &= df['activity_name'] == 'Вывести из черного списка'
df_inter_2 = df[le_masque]
df_inter_2['result_name'].unique()

8)Черный список

в 2018 на действие вывести из черного списка, есть 'в белый список'

In [ ]:
le_masque = df['stage_name'] == 'Черный список'
df_inter = df[le_masque]
df_inter['activity_name'].unique()

In [ ]:
le_masque = df['stage_name'] == 'Черный список'
le_masque &= df['activity_name'] == 'Вывести из черного списка'
df_inter_2 = df[le_masque]
df_inter_2['result_name'].unique()

9)Отказался

In [ ]:
df[(df['result_name'] == 'Отказ кандидата')]

In [ ]:
df[(df['id_applicant'] == 4793759)]

In [ ]:
le_masque = df['stage_name'] == 'Отказался'
df_inter = df[le_masque]
df_inter['activity_name'].unique()

10)Выход на работу

In [ ]:
le_masque = df['stage_name'] == 'Выход на работу'
df_inter = df[le_masque]
df_inter['activity_name'].unique()

11)Мы отказали

In [ ]:
le_masque = df['stage_name'] == 'Мы отказали'
df_inter = df[le_masque]
df_inter['activity_name'].unique()

12)Резерв

In [ ]:
le_masque = df['stage_name'] == 'Резерв'
df_inter = df[le_masque]
df_inter['activity_name'].unique()